[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "*"
hex = "*"
rand = "*"
rand_core="0.6.3"
serde = {version = "*", features = ["derive"]}
pqcrypto-dilithium = "*"
pqcrypto-traits = "*"
base58 = "0.2.0"
tokio = { version = "1.33.0", features = ["full"]}
bincode = "1.3.3"
async-trait = { version = "0.1.74", features = [] }
local-ip-address = "0.5.6"
scrypt = "0.11.0"
num-bigint = "0.4.4"
